# Generated by Django 6.0.5 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BistroMaster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=50, unique=True)),
                ("contrasena", models.CharField(max_length=128)),
            ],
        ),
    ]

