# Generated by Django 6.0.5 on 2026-05-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BistroMaster', '0002_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('tipo_contrato', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Por horas', 'Por horas'), ('Prestación de servicios', 'Prestación de servicios')], max_length=40)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
